---
title: "Assessing Daily Shelter Availability in Toronto: An Occupancy and Capacity Analysis"
subtitle: "Does Toronto has enough Daily Shelter?"
author: 
  - Zixuan Yang
thanks: "Code and data are available at: LINK."
date: today
date-format: long
abstract: "This research examines the challenges facing Toronto's shelter system in meeting the needs of its homeless population. Despite efforts to provide support, issues of overcrowding and capacity constraints persist, exacerbated by factors such as insufficient funding and temporary bed closures. Through an analysis of occupancy rates and capacity utilization, this study aims to identify areas of improvement and inform policy recommendations for enhancing shelter services in Toronto."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(palmerpenguins)
```


# Introduction


Introduction:

Like many urban centers around the world, Toronto faces complex issues such as homelessness and providing shelter services for vulnerable populations. With its diverse and vibrant population, Toronto's housing system plays a crucial role in supporting and sheltering individuals and families facing housing insecurity. The Shelter and Support Services division in Toronto is responsible for overseeing a comprehensive network of overnight shelters and allied services aimed at meeting the urgent needs of the homeless population. At the core of this effort is the Shelter Management Information System (SMIS) database, which provides a daily list of active shelters and overnight service programs operated within the city.

However, despite the existence of these vital services, the Toronto shelter system continues to face ongoing challenges related to occupancy rates and capacity. Demand for shelter often exceeds available resources, leading to overcrowding and tension within shelters. The issue of occupancy in Toronto's shelter system is multifaceted. On one hand, there may be insufficient funding or resources allocated to meet the increasing demand for shelter beds or rooms. Additionally, factors such as maintenance, repairs, renovations, outbreaks, or pest control may temporarily render beds or rooms unavailable, further exacerbating capacity issues.

Given these challenges, a thorough analysis of Toronto's shelter system is necessary to assess whether shelter capacity is sufficient and to identify geographical disparities. This analysis can then inform recommendations to the Toronto government on how to improve shelter system services.



# Data {#sec-data}

The dataset is published on the Toronto open data [@OpenToronto]



# Model

The goal of our modelling strategy is twofold. Firstly,...

Here we briefly describe the Bayesian analysis model used to investigate... Background details and diagnostics are included in [Appendix -@sec-model-details].

## Model set-up

Define $y_i$ as the number of seconds that the plane remained aloft. Then $\beta_i$ is the wing width and $\gamma_i$ is the wing length, both measured in millimeters.  

\begin{align} 
y_i|\mu_i, \sigma &\sim \mbox{Normal}(\mu_i, \sigma) \\
\mu_i &= \alpha + \beta_i + \gamma_i\\
\alpha &\sim \mbox{Normal}(0, 2.5) \\
\beta &\sim \mbox{Normal}(0, 2.5) \\
\gamma &\sim \mbox{Normal}(0, 2.5) \\
\sigma &\sim \mbox{Exponential}(1)
\end{align}

We run the model in R [@citeR] using the `rstanarm` package of @rstanarm. We use the default priors from `rstanarm`.


### Model justification

We expect a positive relationship between the size of the wings and time spent aloft. In particular...

We can use maths by including latex between dollar signs, for instance $\theta$.


# Results



# Discussion

## First discussion point {#sec-first-point}

If my paper were 10 pages, then should be be at least 2.5 pages. The discussion is a chance to show off what you know and what you learnt from all this. 

## Second discussion point

## Third discussion point

## Weaknesses and next steps

Weaknesses and next steps should also be included.

\newpage

\appendix

# Appendix {-}


# Additional data details

# Model details {#sec-model-details}

## Posterior predictive check


## Diagnostics

\newpage


# References


